# Generated by Django 2.2.6 on 2019-10-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_ID', models.IntegerField()),
                ('destination_pincode', models.IntegerField()),
                ('no_of_devices_shipped', models.IntegerField()),
            ],
        ),
    ]
