# Generated by Django 2.2.6 on 2019-10-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191013_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment_details',
            name='status',
            field=models.CharField(choices=[('ready-for-dispatch', 'Ready for dispatch'), ('in-transit', 'In transit'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='r', max_length=20),
        ),
    ]
