# Generated by Django 2.2.6 on 2019-10-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment_details',
            name='status',
            field=models.CharField(choices=[('r', 'Ready for dispatch'), ('t', 'In transit'), ('d', 'Delivered'), ('c', 'Canceled')], default='r', max_length=6),
        ),
    ]
